import type { Metadata } from 'next';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { ConfigProvider } from 'antd';
import { Inter } from 'next/font/google';
import MainLayout from '@/components/MainLayout';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

const theme = {
  color: {
    'primary-100': '#f0f2ff',
    'primary-200': '#d9dbff',
    'primary-500': '#5561e9',
  },
};

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full bg-white">
      <body className={`h-full ${inter.className}`}>
        <div className='md:flex h-full'>
          {/* <Menu />
          <main className="py-4 md:py-8 flex-1 overflow-y-auto m-8 bg-white rounded-md">
            <div className="px-4 md:px-6 md:px-8">
              <AntdRegistry>
                {children}
              </AntdRegistry>
            </div>
          </main> */}
          <ConfigProvider
            theme={{
              token: {
                colorPrimary: theme.color['primary-500'],
                colorLink: theme.color['primary-500'],
                colorBgTextHover: theme.color['primary-200'],
              },
            }}
          >
            <AntdRegistry>
              <MainLayout>
                {children}
              </MainLayout>
            </AntdRegistry>
          </ConfigProvider>
        </div>
      </body>
    </html>
  );
}
